# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

cc_library(
    name = "pir_preprocessed_data",
    hdrs = ["pir_preprocessed_data.h"],
    deps = [
        "//crypto:file_util",
        "//crypto:lwes_to_rlwe",
        "//crypto:matrix",
        "//crypto:polynomial",
        "//crypto:status_macros",
        "//crypto/pir:pir_params",
        "//crypto/proto:pir_server_cc_proto",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
    ],
)

cc_library(
    name = "preprocessing_server",
    hdrs = ["preprocessing_server.h"],
    deps = [
        ":pir_preprocessed_data",
        "//crypto:db_row_interpolation",
        "//crypto:encryption",
        "//crypto:hint_computation",
        "//crypto:lwes_to_rlwe",
        "//crypto:matrix",
        "//crypto:polynomial",
        "//crypto:polynomial_fft",
        "//crypto:status_macros",
        "//crypto/pir:pir_params",
        "@com_github_google_shell_encryption//shell_encryption/prng:chacha_prng",
        "@com_google_absl//absl/memory",
        "@com_google_absl//absl/numeric:bits",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:string_view",
        "@com_google_absl//absl/time",
    ],
)

cc_library(
    name = "pir_server",
    srcs = ["pir_server.cc"],
    hdrs = ["pir_server.h"],
    deps = [
        ":pir_preprocessed_data",
        "//crypto:encryption",
        "//crypto:external_product",
        "//crypto:file_util",
        "//crypto:lwes_to_rlwe",
        "//crypto:matrix",
        "//crypto:polynomial",
        "//crypto:polynomial_fft",
        "//crypto:status_macros",
        "//crypto/pir:pir_params",
        "@com_google_absl//absl/memory",
        "@com_google_absl//absl/numeric:bits",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/time",
    ],
)

cc_test(
    name = "pir_server_test",
    srcs = ["pir_server_test.cc"],
    deps = [
        ":pir_preprocessed_data",
        ":pir_server",
        ":preprocessing_server",
        "//crypto:encryption",
        "//crypto:file_util",
        "//crypto:matrix",
        "//crypto:polynomial",
        "//crypto/pir:pir_params",
        "//crypto/pir/client:pir_client",
        "@com_github_google_shell_encryption//shell_encryption/prng",
        "@com_github_google_shell_encryption//shell_encryption/prng:chacha_prng",
        "@com_github_google_shell_encryption//shell_encryption/testing:matchers",
        "@com_github_google_shell_encryption//shell_encryption/testing:status_testing",
        "@com_google_absl//absl/numeric:bits",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:string_view",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "pir_server_benchmark",
    srcs = ["pir_server_benchmark.cc"],
    deps = [
        ":pir_server",
        ":preprocessing_server",
        "//crypto:encryption",
        "//crypto:external_product",
        "//crypto:lwes_to_rlwe",
        "//crypto:matrix",
        "//crypto:polynomial",
        "//crypto:polynomial_fft",
        "//crypto/pir:pir_params",
        "//crypto/pir/client:pir_client",
        "@com_github_google_shell_encryption//shell_encryption/prng",
        "@com_github_google_shell_encryption//shell_encryption/prng:chacha_prng",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/numeric:bits",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:string_view",
        "@com_google_benchmark//:benchmark",
        "@com_google_googletest//:gtest",
    ],
)
